name: Go Tests and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run Tests
        run: go test -v ./internal/handlers/

      - name: Build Binary
        run: go build -v -o boxed Boxed/cmd/Boxed

      - name: Upload Binary
        uses: actions/upload-artifact
        with:
          name: boxed-binary
          path: boxed
          retention-days: 5