name: Go Tests and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run Tests
        run: go test -v ./internal/handlers/
  
  build-binary:
    name: Build binary
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
      - name: Build Binary
        run: go build -v -o boxed .

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: boxed-binary
          path: boxed
          retention-days: 5